### ISSUE TITLE
Current post double?

### ISSUE THREAD

**Issue by websupporter** [Shelob9/revisions-browser#3]
Hi @Shelob9,
this is great and makes a lot of fun :)

When I click the first time "previous", I get the same post. I am not to close how revisions are stored, but I think the current post is also saved as revision?
![database](https://cloud.githubusercontent.com/assets/6458412/19509117/d567181a-95e5-11e6-9984-a988a442a7f2.jpg)

In this case we wouldn't need to fetch the current post and add it into the `revisions` array. (https://github.com/Shelob9/revisions-browser/blob/master/revision-browser.js#L29-L37)

Do you run into this problem too, or is it something in my local install (not the cleanest right now)?

**Comment by websupporter** [comment]
I did some research:
- `wp_save_post_revision()` is hooked in the action `post_updated`
- `wp_insert_post()` fires `post_updated` if `$update` `true`.
- `$update` is true when a post ID is given.

When I open the editor an auto draft is created (no ID). When I save the auto-draft ID will be taken.

**Comment by websupporter** [comment]
But...
If the posts are created with another editor which might not send an ID (for ex. you can't send an ID to create a post in the REST API, or another plugin using `wp_insert_post()`) the revision creation would not be hit. So, if I am not mistaken, we need to somehow control if the post is already in the revisions array.

**Comment by Shelob9** [comment]
Close via #4
